### ISSUE TITLE
Serverside EMI plugin crash

### ISSUE THREAD

**Issue by DSRLIN** [Low-Drag-MC/LDLib-MultiLoader#22]
I've encountered a crash issue while opening gregtech-modern machine. Seems it was caused by com.lowdragmc.lowdraglib.emi.EMIPlugin.isEmiEnabled.
I've pasted the crash report below.

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2024-04-09 19:42:21
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError: null
	at com.lowdragmc.lowdraglib.emi.EMIPlugin.isEmiEnabled(EMIPlugin.java:32) ~[ldlib-forge-1.20.1-1.0.25.c.jar%23575!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.LDLib.isEmiLoaded(LDLib.java:81) ~[ldlib-forge-1.20.1-1.0.25.c.jar%23575!/:?] {re:classloading,re:mixin}
	at com.lowdragmc.lowdraglib.LDLib.isJeiLoaded(LDLib.java:73) ~[ldlib-forge-1.20.1-1.0.25.c.jar%23575!/:?] {re:classloading,re:mixin}
	at com.gregtechceu.gtceu.api.recipe.ui.GTRecipeTypeUI.lambda$createEditableUITemplate$8(GTRecipeTypeUI.java:220) ~[gtceu-1.20.1-1.2.0.jar%23405!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.gui.editor.IEditableUI$Normal.setupUI(IEditableUI.java:28) ~[gtceu-1.20.1-1.2.0.jar%23405!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.SimpleTieredMachine.lambda$static$2(SimpleTieredMachine.java:375) ~[gtceu-1.20.1-1.2.0.jar%23405!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.gui.editor.EditableMachineUI.setupUI(EditableMachineUI.java:51) ~[gtceu-1.20.1-1.2.0.jar%23405!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.machine.feature.IFancyUIMachine.createMainPage(IFancyUIMachine.java:52) ~[gtceu-1.20.1-1.2.0.jar%23405!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.gui.fancy.FancyMachineUIWidget.setupFancyUI(FancyMachineUIWidget.java:196) ~[gtceu-1.20.1-1.2.0.jar%23405!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.gui.fancy.FancyMachineUIWidget.performNavigation(FancyMachineUIWidget.java:135) ~[gtceu-1.20.1-1.2.0.jar%23405!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.gui.fancy.FancyMachineUIWidget.initWidget(FancyMachineUIWidget.java:90) ~[gtceu-1.20.1-1.2.0.jar%23405!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.initWidget(WidgetGroup.java:349) ~[ldlib-forge-1.20.1-1.0.25.c.jar%23575!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.lowdragmc.lowdraglib.gui.modular.ModularUI.initWidgets(ModularUI.java:205) ~[ldlib-forge-1.20.1-1.0.25.c.jar%23575!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.lowdragmc.lowdraglib.gui.factory.UIFactory.openUI(UIFactory.java:41) ~[ldlib-forge-1.20.1-1.0.25.c.jar%23575!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.gregtechceu.gtceu.api.machine.feature.IUIMachine.tryToOpenUI(IUIMachine.java:26) ~[gtceu-1.20.1-1.2.0.jar%23405!/:?] {re:classloading}
	at com.gregtechceu.gtceu.api.block.MetaMachineBlock.m_6227_(MetaMachineBlock.java:289) ~[gtceu-1.20.1-1.2.0.jar%23405!/:?] {re:mixin,re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:778) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.BlockStateBaseMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.reduce_blockstate_cache_rebuilds.BlockStateBaseMixin,pl:mixin:APP:framedblocks.mixin.json:MixinBlockStateBase,pl:mixin:APP:crafttweaker.mixins.json:common.access.block.AccessBlockStateBase,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:libx:interact,re:classloading,pl:accesstransformer:B,xf:fml:libx:interact}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1057) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.forge_vehicle_packets.ServerGamePacketListenerImplMixin,pl:mixin:APP:forgivingvoid.mixins.json:ServerGamePacketListenerImplAccessor,pl:mixin:APP:badpackets.mixins.json:MixinServerGamePacketListenerImpl,pl:mixin:APP:littletiles.mixins.json:server.network.ServerGamePacketListenerImplAccessor,pl:mixin:APP:littletiles.mixins.json:server.network.ServerGamePacketListenerImplMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23515!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}
Caused by: java.lang.NullPointerException: Cannot invoke "dev.emi.emi.platform.EmiAgnos.isForgeAgnos()" because "dev.emi.emi.platform.EmiAgnos.delegate" is null
	at dev.emi.emi.platform.EmiAgnos.isForge(EmiAgnos.java:34) ~[emi-1.1.4+1.20.1+forge.jar%23370!/:?] {re:classloading}
	at dev.emi.emi.config.EmiConfig.<clinit>(EmiConfig.java:105) ~[emi-1.1.4+1.20.1+forge.jar%23370!/:?] {re:classloading}
	... 35 more

**Comment by yaroslav4167** [comment]
Hello!
I got the same problem. I noticed that I had no ldlib in my mods. I installed ldlib-forge-1.20.1-1.0.25.e.jar and this solved my problem.

**Comment by DSRLIN** [comment]
Thanks for the comment! Fixed in 1.0.25-e.
