### ISSUE TITLE
New JEI crash issue

### ISSUE THREAD

**Issue by HypnoticChris** [Low-Drag-MC/LDLib-MultiLoader#39]
I see that this has been an ongoing battle, and I don't think this specific crash is a duplicate, booting into a world you will crash prior to getting into the world and get this crash error, this doesn't happen on some much older versions of JEI so I can technically use those but some mods require newer versions of JEI so I can't stay in the old versions.

Time: 2024-09-15 14:08:55
Description: Unexpected error

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at mezz.jei.gui.plugins.JeiGuiPlugin.registerGuiHandlers(JeiGuiPlugin.java:22) ~[jei-1.20.1-forge-15.19.0.88.jar%23561!/:15.19.0.88] {re:classloading}
	at mezz.jei.library.load.PluginLoader.lambda$createGuiScreenHelper$9(PluginLoader.java:115) ~[jei-1.20.1-forge-15.19.0.88.jar%23561!/:15.19.0.88] {re:classloading}
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:25) ~[jei-1.20.1-forge-15.19.0.88.jar%23561!/:15.19.0.88] {re:classloading}
	at mezz.jei.library.load.PluginLoader.createGuiScreenHelper(PluginLoader.java:115) ~[jei-1.20.1-forge-15.19.0.88.jar%23561!/:15.19.0.88] {re:classloading}
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:145) ~[jei-1.20.1-forge-15.19.0.88.jar%23561!/:15.19.0.88] {re:classloading}
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:130) ~[jei-1.20.1-forge-15.19.0.88.jar%23561!/:15.19.0.88] {re:classloading}
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:98) ~[jei-1.20.1-forge-15.19.0.88.jar%23561!/:15.19.0.88] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1451) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientplaynethandler_close,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_close,xf:fml:xaerominimap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlejoingame,xf:fml:xaerominimap:xaero_clientplaynethandler_handlemultiblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlemultiblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlelevelchunkwithlight,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlelevelchunkwithlight,xf:fml:xaerominimap:xaero_clientplaynethandler_updatelevelchunk,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_updatelevelchunk,xf:fml:xaerominimap:xaero_clientplaynethandler_queuelightremoval,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_queuelightremoval,xf:fml:xaerominimap:xaero_clientplaynethandler_handleblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handleblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlesetspawn,xf:fml:xaerominimap:xaero_clientplaynethandler_handlelightupdatepacket,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlelightupdatepacket,xf:fml:xaerominimap:xaero_clientlistener_sendcommand,xf:fml:xaerominimap:xaero_clientlistener_commandunsigned,xf:fml:xaerominimap:xaero_clientplaynethandlerclass,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandlerclass,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientplaynethandler_close,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_close,xf:fml:xaerominimap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlejoingame,xf:fml:xaerominimap:xaero_clientplaynethandler_handlemultiblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlemultiblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlelevelchunkwithlight,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlelevelchunkwithlight,xf:fml:xaerominimap:xaero_clientplaynethandler_updatelevelchunk,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_updatelevelchunk,xf:fml:xaerominimap:xaero_clientplaynethandler_queuelightremoval,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_queuelightremoval,xf:fml:xaerominimap:xaero_clientplaynethandler_handleblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handleblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlesetspawn,xf:fml:xaerominimap:xaero_clientplaynethandler_handlelightupdatepacket,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlelightupdatepacket,xf:fml:xaerominimap:xaero_clientlistener_sendcommand,xf:fml:xaerominimap:xaero_clientlistener_commandunsigned,xf:fml:xaerominimap:xaero_clientplaynethandlerclass,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandlerclass,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:mixin,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1106) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.0.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [ldlib-common.mixins.json:jei.RecipesGuiAccessor] from phase [DEFAULT] in config [ldlib-common.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	... 50 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching recipeLayouts:Ljava/util/List; in mezz/jei/gui/recipes/RecipesGui for ldlib-common.mixins.json:jei.RecipesGuiAccessor->@Accessor[FIELD_GETTER]::getRecipeLayouts()Ljava/util/List; [INJECT Applicator Phase -> ldlib-common.mixins.json:jei.RecipesGuiAccessor -> Apply Accessors ->  -> Locate -> ldlib-common.mixins.json:jei.RecipesGuiAccessor->@Accessor[FIELD_GETTER]::getRecipeLayouts()Ljava/util/List;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1389) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1060) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:398) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	... 50 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Just Enough Items (jei), Version: 15.19.0.88
		Issue tracker URL: https://github.com/mezz/JustEnoughItems/issues?q=is%3Aissue
		at TRANSFORMER/jei@15.19.0.88/mezz.jei.gui.plugins.JeiGuiPlugin.registerGuiHandlers(JeiGuiPlugin.java:22)
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at mezz.jei.gui.plugins.JeiGuiPlugin.registerGuiHandlers(JeiGuiPlugin.java:22) ~[jei-1.20.1-forge-15.19.0.88.jar%23561!/:15.19.0.88] {re:classloading}
	at mezz.jei.library.load.PluginLoader.lambda$createGuiScreenHelper$9(PluginLoader.java:115) ~[jei-1.20.1-forge-15.19.0.88.jar%23561!/:15.19.0.88] {re:classloading}
	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:25) ~[jei-1.20.1-forge-15.19.0.88.jar%23561!/:15.19.0.88] {re:classloading}
	at mezz.jei.library.load.PluginLoader.createGuiScreenHelper(PluginLoader.java:115) ~[jei-1.20.1-forge-15.19.0.88.jar%23561!/:15.19.0.88] {re:classloading}
	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:145) ~[jei-1.20.1-forge-15.19.0.88.jar%23561!/:15.19.0.88] {re:classloading}
	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:130) ~[jei-1.20.1-forge-15.19.0.88.jar%23561!/:15.19.0.88] {re:classloading}
	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:98) ~[jei-1.20.1-forge-15.19.0.88.jar%23561!/:15.19.0.88] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1451) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientplaynethandler_close,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_close,xf:fml:xaerominimap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlejoingame,xf:fml:xaerominimap:xaero_clientplaynethandler_handlemultiblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlemultiblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlelevelchunkwithlight,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlelevelchunkwithlight,xf:fml:xaerominimap:xaero_clientplaynethandler_updatelevelchunk,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_updatelevelchunk,xf:fml:xaerominimap:xaero_clientplaynethandler_queuelightremoval,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_queuelightremoval,xf:fml:xaerominimap:xaero_clientplaynethandler_handleblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handleblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlesetspawn,xf:fml:xaerominimap:xaero_clientplaynethandler_handlelightupdatepacket,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlelightupdatepacket,xf:fml:xaerominimap:xaero_clientlistener_sendcommand,xf:fml:xaerominimap:xaero_clientlistener_commandunsigned,xf:fml:xaerominimap:xaero_clientplaynethandlerclass,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandlerclass,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_clientplaynethandler_close,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_close,xf:fml:xaerominimap:xaero_clientplaynethandler_handlejoingame,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlejoingame,xf:fml:xaerominimap:xaero_clientplaynethandler_handlemultiblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlemultiblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlelevelchunkwithlight,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlelevelchunkwithlight,xf:fml:xaerominimap:xaero_clientplaynethandler_updatelevelchunk,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_updatelevelchunk,xf:fml:xaerominimap:xaero_clientplaynethandler_queuelightremoval,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_queuelightremoval,xf:fml:xaerominimap:xaero_clientplaynethandler_handleblockchange,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handleblockchange,xf:fml:xaerominimap:xaero_clientplaynethandler_handlespawnpoint,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlesetspawn,xf:fml:xaerominimap:xaero_clientplaynethandler_handlelightupdatepacket,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandler_handlelightupdatepacket,xf:fml:xaerominimap:xaero_clientlistener_sendcommand,xf:fml:xaerominimap:xaero_clientlistener_commandunsigned,xf:fml:xaerominimap:xaero_clientplaynethandlerclass,xf:fml:xaeroworldmap:xaero_wm_clientplaynethandlerclass,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:mixin,re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:mixin,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.fix_loop_spin_waiting.BlockableEventLoopMixin,pl:mixin:A}

**Comment by screret** [comment]
update LDLib.
